# Server configuration
server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: Votos
  ### RABBIT ###
  rabbitmq:
    virtualhost: /
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false

  profiles:
    #    active: test
    active: development
    include:  application-${spring.profiles.active}.yml

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:db}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:sa}

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

rabbit:
  exchange:
    resultado: resultado

  queue:
    resultado:
      votacao:
        nome: resultado.votacao.queue
        route: resultado.votacao.route
        plq:
          route: resultado.votacao.plq.route
          queue: resultado.votacao.queue.plq
        dlq:
          ttl: 5000
          route: resultado.votacao.dlq.route
          queue: resultado.votacao.queue.dlq
          tentativas: 5